# Site settings
title: Blog by DVG
email: bradley.temple@gmail.com
description: >
  Ruby on Rails Developer based out of Columbus, OH. Enjoys coding,
  video games, cooking and spending time with my wife and son.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dvg.github.io" # the base hostname & protocol for your site
twitter_username: bradleytemple
github_username:  dvg

# Build settings
markdown: kramdown
